name: Generative Tests
description: Runs the generative tests
    
runs:
  using: "composite"
  steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Go
        uses: actions/setup-go@v2
        with:
          go-version: "^1.18"
          check-latest: true

      - name: Run generative tests
        run: |
          echo Actually I only sleep
          sleep 10s
        shell: bash