name: Integration Tests
description: Runs the integration tests
    
runs:
  using: "composite"
  steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Go
        uses: actions/setup-go@v2
        with:
          go-version: "^1.18"
          check-latest: true

      - name: Wait
        run: |
          echo Going to sleep for 5 seconds
          date
          sleep 5s
          echo I woke up
          date
        shell: bash

      - name: Check what is inside
        run: |
          ls
        shell: bash

      - name: Run integration tests
        run: |
          go test -timeout 30s -run ^Test_Integration$ Jabst/github-actions-playground/repos
        shell: bash