name: On Merge to Master or Release Branch

on:
  push:
    branches:
      - main
      - 'releases/**'

jobs:
  builds:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Build
        uses: ./.github/actions/build

  generative-tests:
    runs-on: ubuntu-latest
    needs: [builds]
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Generative tests
        uses: ./.github/actions/generative-test

  unit-tests:
    runs-on: ubuntu-latest
    needs: [builds]
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Run unit tests
        uses: ./.github/actions/unit-test
          
  integration-test:
    needs: [builds]
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Test
        id: integration-test
        uses: ./.github/actions/integration-test
      
  make-docs:
    runs-on: ubuntu-latest
    needs: [generative-tests, unit-tests, integration-test]
    steps:
      - name: Makes docs
        run: |
          echo Will generate the Docs here

  publish-image:
    runs-on: ubuntu-latest
    needs: [make-docs]
    steps:
      - name: Build Image
        run: |
          echo Is Building the image
      
      - name: Push Image
        run: |
          echo Is pushing the image to the docker registry

  deploy-dev:
    runs-on: ubuntu-latest
    needs: [publish-image]
    steps:
      - name: Deploys to Dev
        run: |
          echo Is deploying to dev

  deploy-prod:
    runs-on: ubuntu-latest
    needs: [publish-image]
    steps:
      - name: Deploys to Production
        run: |
          echo Is deploying to prod