name: On Merge to Master or Release Branch

on:
  push:
    branches:
      - main
      - 'releases/**'

jobs:
  builds:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Go
        uses: actions/setup-go@v2
        with:
          go-version: "^1.18"
          check-latest: true

      - name: Builds and lists directory
        run: |
          ls
          go build -o ./bin/hello
          ls ./bin

      - name: Runs built binary
        run: ./bin/hello

  waits-and-test:
    runs-on: ubuntu-latest
    needs: [builds]
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Go
        uses: actions/setup-go@v2
        with:
          go-version: "^1.18"
          check-latest: true

      - name: Wait
        run: |
          echo Going to sleep for 5 seconds
          date
          sleep 5s
          echo I woke up
          date

      - name: Check what is inside
        run: |
          ls

      - name: Run test
        run: |
          go test -v ./main_test.go

  generative-tests:
    runs-on: ubuntu-latest
    needs: [builds]
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Go
        uses: actions/setup-go@v2
        with:
          go-version: "^1.18"
          check-latest: true

      - name: Run generative tests
        run: |
          echo Actually I only sleep
          sleep 10s

  unit-tests:
    runs-on: ubuntu-latest
    needs: [builds]
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Go
        uses: actions/setup-go@v2
        with:
          go-version: "^1.18"
          check-latest: true

      - name: Run unit tests
        run: |
          go test -count=1 -timeout 30s -run ^Test_Unit/s$ Jabst/github-actions-playground/repos -v
          
  integration-test:
    runs-on: ubuntu-latest
    needs: [builds]
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Go
        uses: actions/setup-go@v2
        with:
          go-version: "^1.18"
          check-latest: true

      - name: Wait
        run: |
          echo Going to sleep for 5 seconds
          date
          sleep 5s
          echo I woke up
          date

      - name: Check what is inside
        run: |
          ls

      - name: Run integration tests
        run: |
          go test -timeout 30s -run ^Test_Integration$ Jabst/github-actions-playground/repos
      
  make-docs:
    runs-on: ubuntu-latest
    needs: [generative-tests, unit-tests, integration-test]
    steps:
      - name: Makes docs
        run: |
          echo Will generate the Docs here

  publish-image:
    runs-on: ubuntu-latest
    needs: [make-docs]
    steps:
      - name: Build Image
        run: |
          echo Is Building the image
      
      - name: Push Image
        run: |
          echo Is pushing the image to the docker registry

  deploy-dev:
    runs-on: ubuntu-latest
    needs: [publish-image]
    steps:
      - name: Deploys to Dev
        run: |
          echo Is deploying to dev

  deploy-prod:
    runs-on: ubuntu-latest
    needs: [publish-image]
    steps:
      - name: Deploys to Production
        run: |
          echo Is deploying to prod