name: Does Something

on: push

jobs:
  builds:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Go
        uses: actions/setup-go@v2
        with:
          go-version: "^1.18"
          check-latest: true

      - name: Builds and lists directory
        run: |
          ls
          go build -o ./bin/hello
          ls ./bin

      - run: ./bin/hello

  waits:
    runs-on: ubuntu-latest
    needs: [builds]
    steps:
      - name: Wait
        run: |
          echo Going to sleep for 5 seconds
          date
          sleep 5s
          echo I woke up
          date
      - name: Check what is inside
        run: |
          ls
        