name: On Push to Feature Branch

on:
  push:
    branches-ignore:    
      - main
      - 'releases/**'

jobs:
  builds:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Build
        uses: ./.github/actions/build

  generative-tests:
    runs-on: ubuntu-latest
    needs: [builds]
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Generative tests
        uses: ./.github/actions/generative-test

  unit-tests:
    runs-on: ubuntu-latest
    needs: [builds]
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Run unit tests
        uses: ./.github/actions/unit-test
          
  integration-test:
    needs: [builds]
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Test
        id: integration-test
        uses: ./.github/actions/integration-test

  publish-image:
    runs-on: ubuntu-latest
    needs: [unit-tests, integration-test, generative-tests, waits-and-test]
    name: Publishing image to registry
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Go
        uses: actions/setup-go@v2
        with:
          go-version: "^1.18"
          check-latest: true

      - name: Publish Image to Docker Registry
        run: |
          echo I am publishing image to the registry

        